"""Generate Config/bibentries.tex: short footnote forms (author, year, title).

Venue/journal details are omitted from footnotes; they appear in Section 7 References.
"""

from __future__ import annotations

import re
from pathlib import Path

BIB = Path(__file__).resolve().parents[3] / "2-Dissertation-Draft/03-End/bibliography.tex"
OUT = Path(__file__).resolve().parents[3] / "2-Dissertation-Draft/Config/bibentries.tex"


def strip_href(text: str) -> str:
    return re.sub(r"\\href\{[^{}]*\}\{[^{}]*\}", "", text).strip()


def untextit(text: str) -> str:
    return re.sub(r"\\textit\{([^{}]*)\}", r"\1", text)


def shorten(entry: str) -> str:
    entry = strip_href(entry).rstrip().rstrip(".")
    m = re.match(r"^(.+?)\s*\((\d{4}|n\.d\.)\)\.\s*(.*)$", entry, re.S)
    if not m:
        return entry + "."
    author = m.group(1).strip()
    # Drop trailing period only when it is not an initial (e.g. "W.").
    if author.endswith(".") and not re.search(r"[A-Z]\.$", author):
        author = author[:-1]
    year, rest = m.group(2), m.group(3).strip()

    # Conference / book chapter: In \textit{Venue} ...
    m_in = re.search(r"\s+In\s+\\textit\{([^{}]+)\}", rest)
    if m_in:
        title = untextit(rest[: m_in.start()].strip().rstrip("."))
        return f"{author} ({year}). {title}."

    # Journal article: Title. \textit{Journal}, ...
    m_j = re.match(r"^(.+?)\.\s*\\textit\{([^{}]+)\}", rest)
    if m_j:
        title = untextit(m_j.group(1).strip())
        return f"{author} ({year}). {title}."

    # Book / report: \textit{Title}. Publisher-or-org...
    m_b = re.match(r"^\\textit\{([^{}]+)\}(.*)$", rest)
    if m_b:
        title = m_b.group(1).strip()
        return f"{author} ({year}). {title}."

    # Plain title (e.g. EIP entries after href strip)
    title = untextit(rest).rstrip(".")
    return f"{author} ({year}). {title}."


def main() -> None:
    bib = BIB.read_text(encoding="utf-8")
    entries = re.findall(
        r"\\item\\phantomsection\\label\{ref:(\d+)\} (.+)",
        bib,
    )
    lines = [
        "% Auto-generated by generate_bibentries.py — short footnote forms.",
        "% Format: Author (year). Title. (venue omitted; see Section 7 References)",
        "% !TEX root = ../main.tex",
        r"\makeatletter",
    ]
    for n, text in entries:
        short = shorten(text.strip())
        # Protect special chars already in LaTeX form
        lines.append(f"\\@namedef{{bibentry@{n}}}{{{short}}}")
    lines.append(r"\makeatother")
    lines.append("")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({len(entries)} entries)")
    for n, text in entries[:5]:
        print(f"  [{n}] {shorten(text.strip())}")
    print("  ...")
    for n, text in entries[10:12]:
        print(f"  [{n}] {shorten(text.strip())}")


if __name__ == "__main__":
    main()
