# Generated by Django 5.2.15 on 2026-06-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(max_length=64)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('synthetic', models.BooleanField(default=False)),
                ('imported_at', models.DateTimeField(auto_now=True)),
                ('source_path', models.CharField(blank=True, max_length=512)),
                ('wallet_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'dataset meta',
            },
        ),
        migrations.CreateModel(
            name='WalletRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('wallet', models.CharField(db_index=True, max_length=42)),
                ('success_rate', models.FloatField()),
                ('total_closes', models.PositiveIntegerField()),
                ('wins', models.PositiveIntegerField()),
                ('losses', models.PositiveIntegerField()),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('protocol', models.CharField(max_length=64)),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
    ]
